(circuit) coatcn@ubuntu:~/workspace/circuit_client$ python src/main.py 
INFO:network.websocket_client:正在连接 WebSocket：ws://192.168.8.165:8000/api/v1/devices/commands
ERROR:network.websocket_client:连接时出现意外错误
Traceback (most recent call last):
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/http11.py", line 240, in parse
    status_line = yield from parse_line(read_line)
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/http11.py", line 305, in parse_line
    line = yield from read_line(MAX_LINE_LENGTH)
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/streams.py", line 46, in read_line
    raise EOFError(f"stream ends after {p} bytes, before end of line")
EOFError: stream ends after 0 bytes, before end of line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/client.py", line 316, in parse
    response = yield from Response.parse(
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/http11.py", line 242, in parse
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/coatcn/workspace/circuit_client/src/network/websocket_client.py", line 29, in connect
    self.ws = await connect(ws_url)
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/asyncio/client.py", line 446, in __await_impl__
    await self.connection.handshake(*self.handshake_args)
  File "/home/coatcn/anaconda3/envs/circuit/lib/python3.10/site-packages/websockets/asyncio/client.py", line 104, in handshake
    raise self.protocol.handshake_exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response








(circuit) coatcn@ubuntu:~/workspace/circuit_client$ python src/main.py 
INFO:network.websocket_client:正在连接 WebSocket：ws://192.168.8.165:8000/api/v1/devices/commands
ERROR:network.websocket_client:连接时出现意外错误: did not receive a valid HTTP response